spring:
  application:
    name: v1
  datasource:
    url: jdbc:postgresql://localhost:5432/servidos
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
